services:
  - type: web
    name: line-bot-estimate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: SPREADSHEET_ID
        sync: false 